version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: 
    - image: cimg/node:lts
jobs:
  lint:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t domain314/conint_frontend
  deliver:
    executor: docker/docker
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push domain314/conint_frontend:latest
  deploy:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS
          command: |
            # deploy to AWS

workflows:
  version: 2
  build-test-and-deliver:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          requires:
            - lint
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - deliver:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - deliver
          filters:
            branches:
              only: main
  # deploy:
  #   jobs:
  #     - deploy:
  #         filters:
  #           branches:
  #             only: deploy/production
